//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPCrudUsingEntityMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ArchiesDbEntities : DbContext
    {
        public ArchiesDbEntities()
            : base("name=ArchiesDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_ProductMaster> tb_ProductMaster { get; set; }
    
        public virtual ObjectResult<tb_ProductMaster> GetEditId(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tb_ProductMaster>("GetEditId", idParameter);
        }
    
        public virtual ObjectResult<tb_ProductMaster> GetEditId(Nullable<int> id, MergeOption mergeOption)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tb_ProductMaster>("GetEditId", mergeOption, idParameter);
        }
    
        public virtual ObjectResult<tb_ProductMaster> SP_ADDPRODUCT(string productName, Nullable<System.DateTime> manufaturingDate, string discription, string heading, Nullable<bool> isdeleted, Nullable<int> created, Nullable<System.DateTime> createdOn)
        {
            var productNameParameter = productName != null ?
                new ObjectParameter("ProductName", productName) :
                new ObjectParameter("ProductName", typeof(string));
    
            var manufaturingDateParameter = manufaturingDate.HasValue ?
                new ObjectParameter("ManufaturingDate", manufaturingDate) :
                new ObjectParameter("ManufaturingDate", typeof(System.DateTime));
    
            var discriptionParameter = discription != null ?
                new ObjectParameter("Discription", discription) :
                new ObjectParameter("Discription", typeof(string));
    
            var headingParameter = heading != null ?
                new ObjectParameter("Heading", heading) :
                new ObjectParameter("Heading", typeof(string));
    
            var isdeletedParameter = isdeleted.HasValue ?
                new ObjectParameter("Isdeleted", isdeleted) :
                new ObjectParameter("Isdeleted", typeof(bool));
    
            var createdParameter = created.HasValue ?
                new ObjectParameter("Created", created) :
                new ObjectParameter("Created", typeof(int));
    
            var createdOnParameter = createdOn.HasValue ?
                new ObjectParameter("CreatedOn", createdOn) :
                new ObjectParameter("CreatedOn", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tb_ProductMaster>("SP_ADDPRODUCT", productNameParameter, manufaturingDateParameter, discriptionParameter, headingParameter, isdeletedParameter, createdParameter, createdOnParameter);
        }
    
        public virtual ObjectResult<tb_ProductMaster> SP_ADDPRODUCT(string productName, Nullable<System.DateTime> manufaturingDate, string discription, string heading, Nullable<bool> isdeleted, Nullable<int> created, Nullable<System.DateTime> createdOn, MergeOption mergeOption)
        {
            var productNameParameter = productName != null ?
                new ObjectParameter("ProductName", productName) :
                new ObjectParameter("ProductName", typeof(string));
    
            var manufaturingDateParameter = manufaturingDate.HasValue ?
                new ObjectParameter("ManufaturingDate", manufaturingDate) :
                new ObjectParameter("ManufaturingDate", typeof(System.DateTime));
    
            var discriptionParameter = discription != null ?
                new ObjectParameter("Discription", discription) :
                new ObjectParameter("Discription", typeof(string));
    
            var headingParameter = heading != null ?
                new ObjectParameter("Heading", heading) :
                new ObjectParameter("Heading", typeof(string));
    
            var isdeletedParameter = isdeleted.HasValue ?
                new ObjectParameter("Isdeleted", isdeleted) :
                new ObjectParameter("Isdeleted", typeof(bool));
    
            var createdParameter = created.HasValue ?
                new ObjectParameter("Created", created) :
                new ObjectParameter("Created", typeof(int));
    
            var createdOnParameter = createdOn.HasValue ?
                new ObjectParameter("CreatedOn", createdOn) :
                new ObjectParameter("CreatedOn", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tb_ProductMaster>("SP_ADDPRODUCT", mergeOption, productNameParameter, manufaturingDateParameter, discriptionParameter, headingParameter, isdeletedParameter, createdParameter, createdOnParameter);
        }
    
        public virtual ObjectResult<tb_ProductMaster> SP_EditPostId(Nullable<int> id, string productName, Nullable<System.DateTime> manufaturingDate, string discription, string heading, Nullable<bool> isdeleted, Nullable<int> modified, Nullable<System.DateTime> modifiedOn)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var productNameParameter = productName != null ?
                new ObjectParameter("ProductName", productName) :
                new ObjectParameter("ProductName", typeof(string));
    
            var manufaturingDateParameter = manufaturingDate.HasValue ?
                new ObjectParameter("ManufaturingDate", manufaturingDate) :
                new ObjectParameter("ManufaturingDate", typeof(System.DateTime));
    
            var discriptionParameter = discription != null ?
                new ObjectParameter("Discription", discription) :
                new ObjectParameter("Discription", typeof(string));
    
            var headingParameter = heading != null ?
                new ObjectParameter("Heading", heading) :
                new ObjectParameter("Heading", typeof(string));
    
            var isdeletedParameter = isdeleted.HasValue ?
                new ObjectParameter("Isdeleted", isdeleted) :
                new ObjectParameter("Isdeleted", typeof(bool));
    
            var modifiedParameter = modified.HasValue ?
                new ObjectParameter("Modified", modified) :
                new ObjectParameter("Modified", typeof(int));
    
            var modifiedOnParameter = modifiedOn.HasValue ?
                new ObjectParameter("ModifiedOn", modifiedOn) :
                new ObjectParameter("ModifiedOn", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tb_ProductMaster>("SP_EditPostId", idParameter, productNameParameter, manufaturingDateParameter, discriptionParameter, headingParameter, isdeletedParameter, modifiedParameter, modifiedOnParameter);
        }
    
        public virtual ObjectResult<tb_ProductMaster> SP_EditPostId(Nullable<int> id, string productName, Nullable<System.DateTime> manufaturingDate, string discription, string heading, Nullable<bool> isdeleted, Nullable<int> modified, Nullable<System.DateTime> modifiedOn, MergeOption mergeOption)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var productNameParameter = productName != null ?
                new ObjectParameter("ProductName", productName) :
                new ObjectParameter("ProductName", typeof(string));
    
            var manufaturingDateParameter = manufaturingDate.HasValue ?
                new ObjectParameter("ManufaturingDate", manufaturingDate) :
                new ObjectParameter("ManufaturingDate", typeof(System.DateTime));
    
            var discriptionParameter = discription != null ?
                new ObjectParameter("Discription", discription) :
                new ObjectParameter("Discription", typeof(string));
    
            var headingParameter = heading != null ?
                new ObjectParameter("Heading", heading) :
                new ObjectParameter("Heading", typeof(string));
    
            var isdeletedParameter = isdeleted.HasValue ?
                new ObjectParameter("Isdeleted", isdeleted) :
                new ObjectParameter("Isdeleted", typeof(bool));
    
            var modifiedParameter = modified.HasValue ?
                new ObjectParameter("Modified", modified) :
                new ObjectParameter("Modified", typeof(int));
    
            var modifiedOnParameter = modifiedOn.HasValue ?
                new ObjectParameter("ModifiedOn", modifiedOn) :
                new ObjectParameter("ModifiedOn", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tb_ProductMaster>("SP_EditPostId", mergeOption, idParameter, productNameParameter, manufaturingDateParameter, discriptionParameter, headingParameter, isdeletedParameter, modifiedParameter, modifiedOnParameter);
        }
    
        public virtual ObjectResult<tb_ProductMaster> SP_REMOVEPRODUCT(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tb_ProductMaster>("SP_REMOVEPRODUCT", idParameter);
        }
    
        public virtual ObjectResult<tb_ProductMaster> SP_REMOVEPRODUCT(Nullable<int> id, MergeOption mergeOption)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tb_ProductMaster>("SP_REMOVEPRODUCT", mergeOption, idParameter);
        }
    
        public virtual ObjectResult<tb_ProductMaster> SP_SHOWPRODUCT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tb_ProductMaster>("SP_SHOWPRODUCT");
        }
    
        public virtual ObjectResult<tb_ProductMaster> SP_SHOWPRODUCT(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tb_ProductMaster>("SP_SHOWPRODUCT", mergeOption);
        }
    }
}
