//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPCrudUsingEntityMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ProductMaster
    {
        public int Id { get; set; }
        public string ProductName { get; set; }
        public System.DateTime ManufaturingDate { get; set; }
        public string Discription { get; set; }
        public string Heading { get; set; }
        public Nullable<bool> Isdeleted { get; set; }
        public Nullable<int> Created { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> Modified { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
